### ISSUE TITLE
activity_notify not working

### ISSUE THREAD

**Issue by Patrax** [GetStream/stream-rails#40]
I've tested this getting the target feed to see if it is notified, but it returns no results.
```
	def activity_notify
	  [StreamRails.feed_manager.get_notification_feed(self.target_id)]
	end

feed = StreamRails.feed_manager.get_user_feed(@target.id)
```

**Comment by kennym** [comment]
@Patrax shouldn't it be `feed = StreamRails.feed_manager.get_notification_feed(@target.id)`?

Also, check your logs to look out for any warnings or hints.

**Comment by asmatameem** [comment]
@Patrax : I had the same issue too. I used the example ` stream_rails.rb ` config file which configures the notification feed as `  config.notification_feed = "notifications" `, but in the dashboard the feed group that is created by default is ` notification `. Change your config file to match the name that is given in dashboard - ` notification ` and it should work.

**Comment by tbarbugli** [comment]
fixed the example in the README, thank you for pointing this out!

**Comment by asmatameem** [comment]
@tbarbugli : Thanks for updating it in the README. That fixes the ` get_user_feed ` results, but I still don't see any results in ` StreamRails.feed_manager.get_notification_feed(current_user.id).get() ` ? Any thoughts? I am using the ` stream-example-rails ` app to test this.
